import type { Product } from "./shop";

// Catálogo de respaldo. Se usa mientras no esté conectada la planilla de Google
// (o si la planilla no responde). Costos al 30/9/2026.

const nuevo6 = "6 meses";
const usado3 = "3 meses";

export const fallbackProducts: Product[] = [
  // Celulares · Zona
  { id: "samsung-a06-64", nombre: "Samsung Galaxy A06", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 145, moneda: "USD", detalle: "4 GB · 64 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/220386-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a16-128", nombre: "Samsung Galaxy A16", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 170, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true, foto: "https://samsungar.vtexassets.com/arquivos/ids/220642-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a07-128", nombre: "Samsung Galaxy A07", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 180, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "/img/productos/samsung-a07-128.webp" },
  { id: "samsung-a17-128", nombre: "Samsung Galaxy A17", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 185, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/220689-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a17-256", nombre: "Samsung Galaxy A17", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 265, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/220689-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a36-256", nombre: "Samsung Galaxy A36 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 330, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/221038-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a07-64", nombre: "Samsung Galaxy A07", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 150, moneda: "USD", detalle: "4 GB · 64 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-a17-5g-256", nombre: "Samsung Galaxy A17 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 340, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-a27-5g-256", nombre: "Samsung Galaxy A27 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 325, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-a37-5g-256", nombre: "Samsung Galaxy A37 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 385, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-a56-5g-256", nombre: "Samsung Galaxy A56 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 395, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-a56-5g-12-256", nombre: "Samsung Galaxy A56 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 425, moneda: "USD", detalle: "12 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-a57-5g-256", nombre: "Samsung Galaxy A57 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 420, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true },
  { id: "samsung-s25-ultra-512", nombre: "Samsung Galaxy S25 Ultra", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 940, moneda: "USD", detalle: "12 GB · 512 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-s26-plus-256", nombre: "Samsung Galaxy S26+", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 880, moneda: "USD", detalle: "12 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "samsung-s26-ultra-256", nombre: "Samsung Galaxy S26 Ultra", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 1000, moneda: "USD", detalle: "12 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true },
  { id: "moto-g06-128", nombre: "Motorola Moto G06", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 165, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://armoto.vtexassets.com/arquivos/ids/174019-800-auto?v=639235230936700000&width=800&height=auto&aspect=true" },
  { id: "moto-g15-256", nombre: "Motorola Moto G15", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 190, moneda: "USD", detalle: "4 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true, foto: "https://armoto.vtexassets.com/arquivos/ids/174524-800-auto?v=639231962293800000&width=800&height=auto&aspect=true" },
  { id: "moto-g35-256", nombre: "Motorola Moto G35 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 205, moneda: "USD", detalle: "4 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://armoto.vtexassets.com/arquivos/ids/174511-800-auto?v=639234372130630000&width=800&height=auto&aspect=true" },
  { id: "moto-g56-256", nombre: "Motorola Moto G56 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 275, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "/img/productos/moto-g56-256.webp" },
  { id: "moto-g15-512", nombre: "Motorola Moto G15", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 215, moneda: "USD", detalle: "4 GB · 512 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-g17-power-256", nombre: "Motorola Moto G17 Power", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 255, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-g47-5g-128", nombre: "Motorola Moto G47 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 225, moneda: "USD", detalle: "8 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Viene sin cargador en la caja (lo podés sumar desde Accesorios)." },
  { id: "moto-g56-12-256", nombre: "Motorola Moto G56 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 280, moneda: "USD", detalle: "12 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-g57-5g-256", nombre: "Motorola Moto G57 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 255, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Viene sin cargador en la caja (lo podés sumar desde Accesorios)." },
  { id: "moto-g67-256", nombre: "Motorola Moto G67", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 290, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-g77-256", nombre: "Motorola Moto G77", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 290, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-g86-5g-256", nombre: "Motorola Moto G86 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 295, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Viene sin cargador en la caja (lo podés sumar desde Accesorios).", destacado: true },
  { id: "moto-g86-power-256", nombre: "Motorola Moto G86 Power 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 305, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-edge-60-fusion-256", nombre: "Motorola Edge 60 Fusion 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 305, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-edge-60-pro-256", nombre: "Motorola Edge 60 Pro 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 395, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-edge-70-fusion-256", nombre: "Motorola Edge 70 Fusion 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 420, moneda: "USD", detalle: "12 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "moto-edge-70-256", nombre: "Motorola Edge 70 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 425, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  // Xiaomi e Infinix · Zona
  { id: "redmi-15c-128", nombre: "Xiaomi Redmi 15C", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 175, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "redmi-15c-256", nombre: "Xiaomi Redmi 15C", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 195, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "redmi-15-256", nombre: "Xiaomi Redmi 15", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 235, moneda: "USD", detalle: "8 GB · 256 GB · batería 7000 mAh", plazo: "24 a 48 h", garantia: nuevo6, foto: "/img/productos/redmi-15.webp" },
  { id: "redmi-note-15-256", nombre: "Xiaomi Redmi Note 15", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 255, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "redmi-note-17-256", nombre: "Xiaomi Redmi Note 17", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 260, moneda: "USD", detalle: "6 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "redmi-note-15-pro-256", nombre: "Xiaomi Redmi Note 15 Pro", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 315, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true },
  { id: "redmi-note-15-pro-plus-256", nombre: "Xiaomi Redmi Note 15 Pro+", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 405, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "poco-m8-5g-256", nombre: "Xiaomi Poco M8 5G", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 270, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "poco-x8-pro-256", nombre: "Xiaomi Poco X8 Pro 5G", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 435, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "poco-f8-pro-256", nombre: "Xiaomi Poco F8 Pro 5G", categoria: "celulares", marca: "Xiaomi", estado: "Nuevo", costo: 530, moneda: "USD", detalle: "12 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "infinix-hot-60-pro-256", nombre: "Infinix Hot 60 Pro", categoria: "celulares", marca: "Infinix", estado: "Nuevo", costo: 225, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6 },
  { id: "infinix-note-50-pro-256", nombre: "Infinix Note 50 Pro", categoria: "celulares", marca: "Infinix", estado: "Nuevo", costo: 290, moneda: "USD", detalle: "8 GB · 256 GB · NFC", plazo: "24 a 48 h", garantia: nuevo6 },
  // iPhone · Box y GoaTech (el de Box suma el envío desde Córdoba al costo)
  { id: "iphone-13-128-usado", nombre: "iPhone 13", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 309, moneda: "USD", detalle: "128 GB · batería 82–100%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", destacado: true, foto: "/img/productos/iphone-13-128-usado.webp" },
  { id: "iphone-13-pro-128-usado", nombre: "iPhone 13 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 390, moneda: "USD", detalle: "128 GB · batería 100%", plazo: "24 a 48 h", garantia: usado3, nota: "Revisado en el taller antes de entregarlo.", foto: "/img/productos/iphone-13-pro-128-usado.webp" },
  { id: "iphone-13-pro-max-256-usado", nombre: "iPhone 13 Pro Max", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 519, moneda: "USD", detalle: "256 GB · batería 100%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo.", destacado: true, foto: "/img/productos/iphone-13-pro-max-256-usado.webp" },
  // iPhone 11 y 12: se consiguen por encargue según stock del día (precio y batería por WhatsApp).
  { id: "iphone-12-pro-usado", nombre: "iPhone 12 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 0, moneda: "USD", consultar: true, detalle: "128 GB", plazo: "Por encargue, según stock", garantia: usado3, nota: "Te pasamos precio, color y % de batería por WhatsApp antes de confirmar." },
  { id: "iphone-12-usado", nombre: "iPhone 12", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 0, moneda: "USD", consultar: true, detalle: "64 o 128 GB", plazo: "Por encargue, según stock", garantia: usado3, nota: "Te pasamos precio, color y % de batería por WhatsApp antes de confirmar." },
  { id: "iphone-11-usado", nombre: "iPhone 11", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 0, moneda: "USD", consultar: true, detalle: "64 o 128 GB", plazo: "Por encargue, según stock", garantia: usado3, nota: "Te pasamos precio, color y % de batería por WhatsApp antes de confirmar." },
  // iPhone usados (Box) y sellados (Zona / Box), costos al 29/9/2026
  { id: "iphone-14-128-usado", nombre: "iPhone 14", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 369, moneda: "USD", detalle: "128 GB · batería 84%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", foto: "/img/productos/iphone-14.webp" },
  { id: "iphone-14-pro-128-usado", nombre: "iPhone 14 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 459, moneda: "USD", detalle: "128 GB · batería 80–88%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", foto: "/img/productos/iphone-14-pro.webp" },
  { id: "iphone-15-128-usado", nombre: "iPhone 15", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 469, moneda: "USD", detalle: "128 GB · batería 85–88%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", destacado: true, foto: "/img/productos/iphone-15.webp" },
  { id: "iphone-15-pro-128-usado", nombre: "iPhone 15 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 589, moneda: "USD", detalle: "128 GB · batería 82–87%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", foto: "/img/productos/iphone-15-pro.webp" },
  { id: "iphone-16-128-usado", nombre: "iPhone 16", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 639, moneda: "USD", detalle: "128 GB · batería 86–89%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", foto: "/img/productos/iphone-16.webp" },
  { id: "iphone-16-pro-128-usado", nombre: "iPhone 16 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 729, moneda: "USD", detalle: "128 GB · batería 88–90%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", destacado: true, foto: "/img/productos/iphone-16-pro.webp" },
  { id: "iphone-16-pro-max-256-usado", nombre: "iPhone 16 Pro Max", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 869, moneda: "USD", detalle: "256 GB · batería 88–93%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", foto: "/img/productos/iphone-16-pro-max.webp" },
  { id: "iphone-17-256-usado", nombre: "iPhone 17", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 809, moneda: "USD", detalle: "256 GB · batería 98%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo.", foto: "/img/productos/iphone-17.webp" },
  { id: "iphone-17-pro-max-256-usado", nombre: "iPhone 17 Pro Max", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 1169, moneda: "USD", detalle: "256 GB · batería 98%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo.", foto: "/img/productos/iphone-17-pro-max.webp" },
  { id: "iphone-15-128-sellado", nombre: "iPhone 15", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 750, moneda: "USD", detalle: "128 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja.", foto: "/img/productos/iphone-15.webp" },
  { id: "iphone-16-128-sellado", nombre: "iPhone 16", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 849, moneda: "USD", detalle: "128 GB", plazo: "3 a 5 días hábiles", garantia: nuevo6, nota: "Sellado en caja.", foto: "/img/productos/iphone-16.webp" },
  { id: "iphone-17e-256-sellado", nombre: "iPhone 17e", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 780, moneda: "USD", detalle: "256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja." },
  { id: "iphone-17-256-sellado", nombre: "iPhone 17", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 1000, moneda: "USD", detalle: "256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja.", foto: "/img/productos/iphone-17.webp" },
  { id: "iphone-17-pro-256-sellado", nombre: "iPhone 17 Pro", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 1230, moneda: "USD", detalle: "256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja.", foto: "/img/productos/iphone-17-pro-max.webp" },
  { id: "iphone-17-pro-max-256-sellado", nombre: "iPhone 17 Pro Max", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 1310, moneda: "USD", detalle: "256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja.", destacado: true, foto: "/img/productos/iphone-17-pro-max.webp" },
  { id: "iphone-18-pro-256-sellado", nombre: "iPhone 18 Pro", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 1450, moneda: "USD", detalle: "256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja." },
  { id: "iphone-18-pro-max-256-sellado", nombre: "iPhone 18 Pro Max", categoria: "celulares", marca: "Apple", estado: "Sellado", costo: 1700, moneda: "USD", detalle: "256 GB", plazo: "24 a 48 h", garantia: nuevo6, nota: "Sellado en caja." },

  // Audio · Onpres
  { id: "airpods-4", nombre: "AirPods 4", categoria: "audio", marca: "Apple", estado: "Sellado", costo: 130, moneda: "USD", detalle: "Originales, versión EE.UU.", plazo: "2 a 4 días hábiles", garantia: nuevo6, destacado: true, foto: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-down-compare-202409?wid=600&hei=600&fmt=jpeg&qlt=90" },
  { id: "airpods-4-anc", nombre: "AirPods 4 con cancelación de ruido", categoria: "audio", marca: "Apple", estado: "Sellado", costo: 190, moneda: "USD", detalle: "Originales, versión EE.UU.", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-up-compare-202409?wid=600&hei=600&fmt=jpeg&qlt=90" },

  // Mac · Onpres
  { id: "mac-mini-m4", nombre: "Mac mini M4", categoria: "mac", marca: "Apple", estado: "Sellado", costo: 1030, moneda: "USD", detalle: "16 GB · 512 GB SSD", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-mini-chip-unselect-202608-gallery-1?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1785998455498" },
  { id: "macbook-air-m5-13", nombre: "MacBook Air M5 13\"", categoria: "mac", marca: "Apple", estado: "Sellado", costo: 1400, moneda: "USD", detalle: "16 GB · 512 GB SSD", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Teclado en inglés (versión EE.UU.).", foto: "/img/productos/macbook-air-m5-13.webp" },

  // Accesorios · DistriLand y GoaTech (precios fijos ajustados al mercado)
  { id: "templado-9d", nombre: "Vidrio templado Full 9D", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 1040, moneda: "ARS", precio: 6900, compat: "Samsung línea A, Motorola línea G, iPhone 11 a 13. Consultá tu modelo.", plazo: "Por encargue, 2 a 4 días", garantia: nuevo6, nota: "La colocación va de regalo en el taller.", destacado: true, foto: "/img/productos/templado-9d.webp" },
  { id: "funda-antishock", nombre: "Funda transparente antishock", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 2280, moneda: "ARS", precio: 8900, compat: "Samsung línea A, Motorola línea G, iPhone 11 a 13. Consultá tu modelo.", plazo: "Por encargue, 2 a 4 días", garantia: nuevo6, foto: "/img/productos/funda-antishock.webp" },
  { id: "cable-c-lightning", nombre: "Cable USB-C a Lightning 1 m", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 4670, moneda: "ARS", precio: 11900, compat: "iPhone con conector Lightning (hasta iPhone 14)", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/6132-cable-iphone-tipo-c-a-lightning-generico-con-logo-en-caja-1-mt-3-dd6bfea41c616dbe8917271200435992-640-0.webp" },
  { id: "cable-c-c", nombre: "Cable USB-C a USB-C 1 m", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 5700, moneda: "ARS", precio: 11900, compat: "iPhone 15 en adelante y Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/6133-cable-iphone-tipo-c-a-tipo-c-generico-con-logo-en-caja-1-mt-1-52fe7af2778f749bb717271201978123-640-0.webp" },
  { id: "cable-c-c-motorola", nombre: "Cable USB-C a USB-C Motorola", categoria: "accesorios", marca: "Motorola", estado: "Nuevo", costo: 7840, moneda: "ARS", compat: "Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Original.", foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/5553-cable-tipo-c-a-tipo-c-motorola-original-negro-21-b41c2e80d4d444b78b16667084455493-640-0.webp" },
  { id: "cargador-ngtech-lightning", nombre: "Cargador NGTech 2.1A con cable Lightning", categoria: "accesorios", marca: "NGTech", estado: "Nuevo", costo: 6220, moneda: "ARS", compat: "iPhone con conector Lightning", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/4685-cargador-de-pared-con-cable-lightning-ngtech-carga-rapida-2-1a_71-fc078ff47cedacb94e16354280359187-640-0.webp" },
  { id: "cargador-ngtech-c", nombre: "Cargador NGTech 2.1A con cable USB-C", categoria: "accesorios", marca: "NGTech", estado: "Nuevo", costo: 6610, moneda: "ARS", compat: "Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/4686-cargador-de-pared-con-cable-tipo-c-ngtech-carga-rapida-2-1a_81-ab60ddd320bf46b47116354282415248-640-0.webp" },
  { id: "cargador-motorola-20w", nombre: "Cargador Motorola 20W", categoria: "accesorios", marca: "Motorola", estado: "Nuevo", costo: 13890, moneda: "ARS", compat: "Motorola y Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Original (MC-206).", foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/5549-cargador-de-pared-motorola-mc-206-adaptador-3000-mah-20w-negro-original1-3205748db6ed27bfca16667147703347-640-0.webp" },
  { id: "cargador-motorola-33w", nombre: "Cargador Motorola 33W", categoria: "accesorios", marca: "Motorola", estado: "Nuevo", costo: 22510, moneda: "ARS", compat: "Motorola con TurboPower", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Original (MC-336).", foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/5562-cargador-de-pared-motorola-mc-336-adaptador-3000-mah-33w-tipo-c-negro-original1-20a360433feae2efe216667155084878-640-0.webp" },
  { id: "cargador-20w-apple", nombre: "Cargador 20W USB-C para iPhone", categoria: "accesorios", marca: "Apple", estado: "Nuevo", costo: 19, moneda: "USD", compat: "iPhone 8 en adelante", plazo: "24 a 48 h", garantia: nuevo6, nota: "Original.", foto: "/img/productos/cargador-20w-apple.webp" },
];
