import type { Product } from "./shop";

// Catálogo de respaldo. Se usa mientras no esté conectada la planilla de Google
// (o si la planilla no responde). Costos al 30/9/2026.

const nuevo6 = "6 meses";
const usado3 = "3 meses";

export const fallbackProducts: Product[] = [
  // Celulares · Zona
  { id: "samsung-a06-64", nombre: "Samsung Galaxy A06", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 145, moneda: "USD", detalle: "4 GB · 64 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/220386-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a16-128", nombre: "Samsung Galaxy A16", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 170, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true, foto: "https://samsungar.vtexassets.com/arquivos/ids/220642-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a07-128", nombre: "Samsung Galaxy A07", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 180, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "/img/productos/samsung-a07-128.webp" },
  { id: "samsung-a17-128", nombre: "Samsung Galaxy A17", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 185, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/220689-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a17-256", nombre: "Samsung Galaxy A17", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 265, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/220689-600-auto?width=600&height=auto&aspect=true" },
  { id: "samsung-a36-256", nombre: "Samsung Galaxy A36 5G", categoria: "celulares", marca: "Samsung", estado: "Nuevo", costo: 330, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://samsungar.vtexassets.com/arquivos/ids/221038-600-auto?width=600&height=auto&aspect=true" },
  { id: "moto-g06-128", nombre: "Motorola Moto G06", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 165, moneda: "USD", detalle: "4 GB · 128 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://armoto.vtexassets.com/arquivos/ids/174019-800-auto?v=639235230936700000&width=800&height=auto&aspect=true" },
  { id: "moto-g15-256", nombre: "Motorola Moto G15", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 190, moneda: "USD", detalle: "4 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, destacado: true, foto: "https://armoto.vtexassets.com/arquivos/ids/174524-800-auto?v=639231962293800000&width=800&height=auto&aspect=true" },
  { id: "moto-g35-256", nombre: "Motorola Moto G35 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 205, moneda: "USD", detalle: "4 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "https://armoto.vtexassets.com/arquivos/ids/174511-800-auto?v=639234372130630000&width=800&height=auto&aspect=true" },
  { id: "moto-g56-256", nombre: "Motorola Moto G56 5G", categoria: "celulares", marca: "Motorola", estado: "Nuevo", costo: 275, moneda: "USD", detalle: "8 GB · 256 GB", plazo: "24 a 48 h", garantia: nuevo6, foto: "/img/productos/moto-g56-256.webp" },
  // iPhone · Box y GoaTech (el de Box suma el envío desde Córdoba al costo)
  { id: "iphone-13-128-usado", nombre: "iPhone 13", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 309, moneda: "USD", detalle: "128 GB · batería 82–100%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo. Te pasamos el % de batería exacto por WhatsApp.", destacado: true, foto: "/img/productos/iphone-13-128-usado.webp" },
  { id: "iphone-13-pro-128-usado", nombre: "iPhone 13 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 390, moneda: "USD", detalle: "128 GB · batería 100%", plazo: "24 a 48 h", garantia: usado3, nota: "Revisado en el taller antes de entregarlo.", foto: "/img/productos/iphone-13-pro-128-usado.webp" },
  { id: "iphone-13-pro-max-256-usado", nombre: "iPhone 13 Pro Max", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 519, moneda: "USD", detalle: "256 GB · batería 100%", plazo: "3 a 5 días hábiles", garantia: usado3, nota: "Revisado en el taller antes de entregarlo.", destacado: true, foto: "/img/productos/iphone-13-pro-max-256-usado.webp" },
  // iPhone 11 y 12: se consiguen por encargue según stock del día (precio y batería por WhatsApp).
  { id: "iphone-12-pro-usado", nombre: "iPhone 12 Pro", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 0, moneda: "USD", consultar: true, detalle: "128 GB", plazo: "Por encargue, según stock", garantia: usado3, nota: "Te pasamos precio, color y % de batería por WhatsApp antes de confirmar." },
  { id: "iphone-12-usado", nombre: "iPhone 12", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 0, moneda: "USD", consultar: true, detalle: "64 o 128 GB", plazo: "Por encargue, según stock", garantia: usado3, nota: "Te pasamos precio, color y % de batería por WhatsApp antes de confirmar." },
  { id: "iphone-11-usado", nombre: "iPhone 11", categoria: "celulares", marca: "Apple", estado: "Reacondicionado", costo: 0, moneda: "USD", consultar: true, detalle: "64 o 128 GB", plazo: "Por encargue, según stock", garantia: usado3, nota: "Te pasamos precio, color y % de batería por WhatsApp antes de confirmar." },

  // Audio · Onpres
  { id: "airpods-4", nombre: "AirPods 4", categoria: "audio", marca: "Apple", estado: "Sellado", costo: 130, moneda: "USD", detalle: "Originales, versión EE.UU.", plazo: "2 a 4 días hábiles", garantia: nuevo6, destacado: true, foto: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-down-compare-202409?wid=600&hei=600&fmt=jpeg&qlt=90" },
  { id: "airpods-4-anc", nombre: "AirPods 4 con cancelación de ruido", categoria: "audio", marca: "Apple", estado: "Sellado", costo: 190, moneda: "USD", detalle: "Originales, versión EE.UU.", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-up-compare-202409?wid=600&hei=600&fmt=jpeg&qlt=90" },

  // Mac · Onpres
  { id: "mac-mini-m4", nombre: "Mac mini M4", categoria: "mac", marca: "Apple", estado: "Sellado", costo: 1030, moneda: "USD", detalle: "16 GB · 512 GB SSD", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/mac-mini-chip-unselect-202608-gallery-1?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1785998455498" },
  { id: "macbook-air-m5-13", nombre: "MacBook Air M5 13\"", categoria: "mac", marca: "Apple", estado: "Sellado", costo: 1400, moneda: "USD", detalle: "16 GB · 512 GB SSD", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Teclado en inglés (versión EE.UU.).", foto: "/img/productos/macbook-air-m5-13.webp" },

  // Accesorios · DistriLand y GoaTech (precios fijos ajustados al mercado)
  { id: "templado-9d", nombre: "Vidrio templado Full 9D", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 1040, moneda: "ARS", precio: 6900, compat: "Samsung línea A, Motorola línea G, iPhone 11 a 13. Consultá tu modelo.", plazo: "Por encargue, 2 a 4 días", garantia: nuevo6, nota: "La colocación va de regalo en el taller.", destacado: true, foto: "/img/productos/templado-9d.webp" },
  { id: "funda-antishock", nombre: "Funda transparente antishock", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 2280, moneda: "ARS", precio: 8900, compat: "Samsung línea A, Motorola línea G, iPhone 11 a 13. Consultá tu modelo.", plazo: "Por encargue, 2 a 4 días", garantia: nuevo6, foto: "/img/productos/funda-antishock.webp" },
  { id: "cable-c-lightning", nombre: "Cable USB-C a Lightning 1 m", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 4670, moneda: "ARS", precio: 11900, compat: "iPhone con conector Lightning (hasta iPhone 14)", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/6132-cable-iphone-tipo-c-a-lightning-generico-con-logo-en-caja-1-mt-3-dd6bfea41c616dbe8917271200435992-640-0.webp" },
  { id: "cable-c-c", nombre: "Cable USB-C a USB-C 1 m", categoria: "accesorios", marca: "Genérico", estado: "Nuevo", costo: 5700, moneda: "ARS", precio: 11900, compat: "iPhone 15 en adelante y Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/6133-cable-iphone-tipo-c-a-tipo-c-generico-con-logo-en-caja-1-mt-1-52fe7af2778f749bb717271201978123-640-0.webp" },
  { id: "cable-c-c-motorola", nombre: "Cable USB-C a USB-C Motorola", categoria: "accesorios", marca: "Motorola", estado: "Nuevo", costo: 7840, moneda: "ARS", compat: "Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Original.", foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/5553-cable-tipo-c-a-tipo-c-motorola-original-negro-21-b41c2e80d4d444b78b16667084455493-640-0.webp" },
  { id: "cargador-ngtech-lightning", nombre: "Cargador NGTech 2.1A con cable Lightning", categoria: "accesorios", marca: "NGTech", estado: "Nuevo", costo: 6220, moneda: "ARS", compat: "iPhone con conector Lightning", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/4685-cargador-de-pared-con-cable-lightning-ngtech-carga-rapida-2-1a_71-fc078ff47cedacb94e16354280359187-640-0.webp" },
  { id: "cargador-ngtech-c", nombre: "Cargador NGTech 2.1A con cable USB-C", categoria: "accesorios", marca: "NGTech", estado: "Nuevo", costo: 6610, moneda: "ARS", compat: "Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/4686-cargador-de-pared-con-cable-tipo-c-ngtech-carga-rapida-2-1a_81-ab60ddd320bf46b47116354282415248-640-0.webp" },
  { id: "cargador-motorola-20w", nombre: "Cargador Motorola 20W", categoria: "accesorios", marca: "Motorola", estado: "Nuevo", costo: 13890, moneda: "ARS", compat: "Motorola y Android con USB-C", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Original (MC-206).", foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/5549-cargador-de-pared-motorola-mc-206-adaptador-3000-mah-20w-negro-original1-3205748db6ed27bfca16667147703347-640-0.webp" },
  { id: "cargador-motorola-33w", nombre: "Cargador Motorola 33W", categoria: "accesorios", marca: "Motorola", estado: "Nuevo", costo: 22510, moneda: "ARS", compat: "Motorola con TurboPower", plazo: "2 a 4 días hábiles", garantia: nuevo6, nota: "Original (MC-336).", foto: "https://acdn-us.mitiendanube.com/stores/288/942/products/5562-cargador-de-pared-motorola-mc-336-adaptador-3000-mah-33w-tipo-c-negro-original1-20a360433feae2efe216667155084878-640-0.webp" },
  { id: "cargador-20w-apple", nombre: "Cargador 20W USB-C para iPhone", categoria: "accesorios", marca: "Apple", estado: "Nuevo", costo: 19, moneda: "USD", compat: "iPhone 8 en adelante", plazo: "24 a 48 h", garantia: nuevo6, nota: "Original.", foto: "/img/productos/cargador-20w-apple.webp" },
];
